config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/help', to: 'static_pages#help', as: 'help'

  get '/signup', to: 'authors#new', as: 'signup'
  post '/signup', to: 'authors#create', as: 'register'

  get    '/login',   to: 'sessions#new', as: 'signin'
  post   '/login',   to: 'sessions#create', as: 'login'
  delete '/logout',  to: 'sessions#destroy', as: 'logout'

  get '/feed', to: 'authors#feed', as: 'feed'

  resources :articles

  # resources :authors
  resources :authors do
    member do
      get :following, :followers, :favorites
    end
  end

  resources :follows, only: [:create, :destroy]

  resources :favorites, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/', to: 'static_pages#home', as: 'home'
  root 'static_pages#home'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @feed_items = Article.joins(:favoraiters)
                         .group('favorites.article_id')
                         .order('COUNT(*)')
                         .limit(12)
  end

  def about
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_feed.html.erb
<% cache article do %>
    <div class="col-sm-6 col-md-4" id="article-<%= article.id %>">
    <div class="thumbnail">
      <%= image_tag article.default_picture? ? article.default_picture.url : article.default_image_url %>
      <div class="caption">
        <span class='author'><%= link_to article.author.name, article.author %></span>
        <h4 class='title'><%= link_to article.title, article %></h4>
        <p><%= raw(article.content.truncate(20)) %></p>
        <span class='timestamp'>
           <%= time_ago_in_words(article.created_at) %> ago.
      </span>
        <p>
          <%= link_to 'Read More...',
                      article,
                      class: 'btn btn-primary' %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About SharedBlog</h1>

<h3>
  This app was created as assignment, requirements as following:
</h3>

<h6>
  Create a Rails application with the following features.
</h6>

<ul>
  <li>
    User can signs up.
  </li>

  <li>
  User can sign in.
  </li>

  <li>
  User can create Articles.
  </li>

  <li>
    User can list all Articles.
  </li>

  <li>
    User can read an Article.
  </li>

  <li>
    User can favorite/unfavorite Article.
  </li>

  <li>
    User can list all his favorite Articles.
  </li>

  <li>
    User can follow/unfollow other users.
  </li>

  <li>
    User can list his followings.
  </li>

  <li>
    User can list Articles from his followings.
  </li>

</ul>


 <strong>
   Note:
 </strong>

<p>
  Listing Articles should display owner, title, content and favorites count.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  This is a sample help page, it won't help you in any ways :\
  <br>
  To get real help , see the
  <a href="http://guides.rubyonrails.org"><em>Ruby on Rails </em>
    Guide</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the SharedBlog</h1>

  <h2>
    This is the home page for the
    <a href="#">SharedBlog</a>
    sample application.
  </h2>
  <% if logged_in? %>
      <%= link_to 'Read All Articles!', articles_path, class: 'btn btn-lg btn-primary' %>
  <% else %>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
  <% end %>
</div>

<% if @feed_items.any? %>
    <div class="row">
      <% cache @feed_items do %>
          <% @feed_items.each do |article| -%>
              <% cache article do %>
                  <%= render 'feed', :article => article %>
              <% end %>
          <% end %>
      <% end %>
    </div>
<% end %>