config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/help', to: 'static_pages#help', as: 'help'

  get '/signup', to: 'authors#new', as: 'signup'
  post '/signup', to: 'authors#create', as: 'register'

  get    '/login',   to: 'sessions#new', as: 'signin'
  post   '/login',   to: 'sessions#create', as: 'login'
  delete '/logout',  to: 'sessions#destroy', as: 'logout'

  get '/feed', to: 'authors#feed', as: 'feed'

  resources :articles

  # resources :authors
  resources :authors do
    member do
      get :following, :followers, :favorites
    end
  end

  resources :follows, only: [:create, :destroy]

  resources :favorites, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/', to: 'static_pages#home', as: 'home'
  root 'static_pages#home'
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :favoriting_author, class_name:  'Favorite',
                               foreign_key: 'article_id',
                               dependent: :destroy
  has_many :favoraiters, through: :favoriting_author,
                         source: :author

  belongs_to :author

  default_scope -> { order(created_at: :desc) }

  mount_uploader :default_picture, PictureUploader

  validates :author_id, presence: true
  validates :title, presence: true, length: { maximum: 150 }
  validates :content, presence: true, length: { minimum: 300 }
  validate  :picture_size

  def default_image_url
    ['default_article.jpg'].compact.join('_')
  end

  private

  # Validates the size of an uploaded picture.
  def picture_size
    if default_picture.size > 5.megabytes
      errors.add(:default_picture, 'should be less than 5MB')
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :logged_in_author, only: [:new, :update, :edit, :create, :destroy]
  before_action :correct_author, only: [:destroy, :edit]
  before_action :prepare_article, only: [:show, :edit, :update]

  def index
    @articles = Article.all.paginate(page: params[:page], per_page: 10)
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_author.articles.build(article_params)
    if @article.save
      flash[:success] = 'Article created!'
      redirect_back_or author_path(current_author)
    else
      # @feed_items = current_author.articles.paginate(page: params[:page], per_page: 10)
      render 'articles/new'
    end
  end

  def destroy
    @article.destroy # unless @article.nil?
    flash[:success] = 'Article deleted!'
    redirect_to request.referrer || root_url
  end

  def show
  end

  def edit
  end

  def update
    if @article.update_attributes(article_params)
      flash[:success] = 'Article updated'
      redirect_to @article
    else
      render 'edit'
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :default_picture)
  end

  def correct_author
    if current_author.admin
      @article = Article.find_by(id: params[:id])
    else
      @article = current_author.articles.find_by(id: params[:id])
      redirect_to root_url if @article.nil?
    end
  end

  def prepare_article
    @article = Article.find(params[:id])
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<% cache article do %>
<li id="article-<%= article.id %>">
  <%= link_to gravatar_for(article.author, size: 50), article.author %>
  <span class='author'><%= link_to article.author.name, article.author %></span>
  <h4 class='title'><%= link_to article.title, article %></h4>
  <span class='content'>
    <%= image_tag article.default_picture? ? article.default_picture.url : article.default_image_url %>
    <br>
    <%= raw(article.content.truncate(50)) %>
    <br>
    <br>
    <br>
  </span>
  <div>
  <span class='timestamp'>
    Published <%= time_ago_in_words(article.created_at) %> ago.
  </span>
  </div>
  <br>
  <div>
    <span class='read_more'><%= link_to 'Read More...',
                                        article,
                                        class: 'btn btn-primary' %>
    </span>
  </div>
</li>
<% end %>

app/views/articles/_article_details.html.erb
<% cache article do %>
<li id="article-<%= article.id %>">
  <h3><%= article.title %></h3>
  <span class='content'>
    <center>
    <%= image_tag article.default_picture? ? article.default_picture.url : article.default_image_url %>
    </center>
      <br>
    <br>
    <br>
    <%= raw(article.content) %>
  </span>

  <span class='timestamp'>
    Published <%= time_ago_in_words(article.created_at) %> ago.
  </span>
  <br>
  <div>
    <% if current_author&.admin? || current_author?(article.author) %>
      <span class='delete'>
        <%= link_to 'Edit', edit_article_path(article),
                    class: 'btn btn-default' %>

        <%= link_to 'delete',
                    article,
                    class: 'btn btn-danger',
                    method: :delete,
                    data: { confirm: 'You sure?' } %>
      </span>
    <% end %>
  </div>
</li>
<% end %>

app/views/articles/_favorite.html.erb
<%= form_for(current_author.favorite_articles.build, remote: true) do |f| %>
    <div><%= hidden_field_tag :article_id, @article.id %></div>
    <%= f.submit 'Favorite', class: 'btn btn-primary' %>
<% end %>

app/views/articles/_favorite_form.html.erb
<% unless current_publisher?(@article) %>
    <div id="favorite_form">
      <% if current_author.favoring?(@article) %>
          <%= render 'unfavorite' %>
      <% else %>
          <%= render 'favorite' %>
      <% end %>
    </div>
<% end %>

app/views/articles/_form.html.erb
<h3>Add New Article</h3>
<%= simple_form_for(@article) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_field :title, placeholder: 'Choose article\'s title'  %>
    </div>
    <div class="field">
      <%= f.input :content, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: 'form-control' %>
    </div>
    <%= f.submit 'Done', class: 'btn btn-primary' %>
    <span class="default_picture">
      <%= f.file_field :default_picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
    $('#article_default_picture').bind('change', function() {
        var size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file.');
        }
    });
</script>

app/views/articles/_unfavorite.html.erb
<%= form_for(current_author.favorite_articles.find_by(article_id: @article.id),
             html: { method: :delete }, remote: true) do |f| %>
    <%= f.submit 'Unfavorite', class: 'btn' %>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="col-md-12">
  <% if @articles.any? %>
      <h3>All Articles (<%= @articles.count %>)</h3>
      <ol class="articles">
        <% cache @articles do %>
          <%= render @articles %>
        <% end %>
      </ol>
      <%= will_paginate @articles %>
  <% end %>
</div>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>
<% cache @article do %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>
        Author:
        <%= gravatar_for @article.author %>
        <%= @article.author.name %>
      </h1>
    </section>
    <hr>
    <section class="stats">
      <%= render 'shared/favorited' %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'favorite_form' if logged_in? %>
    <ol class="articles">
      <%= render 'article_details', :article => @article %>
    </ol>
  </div>
</div>
<% end %>