config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/help', to: 'static_pages#help', as: 'help'

  get '/signup', to: 'authors#new', as: 'signup'
  post '/signup', to: 'authors#create', as: 'register'

  get    '/login',   to: 'sessions#new', as: 'signin'
  post   '/login',   to: 'sessions#create', as: 'login'
  delete '/logout',  to: 'sessions#destroy', as: 'logout'

  get '/feed', to: 'authors#feed', as: 'feed'

  resources :articles

  # resources :authors
  resources :authors do
    member do
      get :following, :followers, :favorites
    end
  end

  resources :follows, only: [:create, :destroy]

  resources :favorites, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/', to: 'static_pages#home', as: 'home'
  root 'static_pages#home'
end

app/views/shared/_article_form.html.erb
<%= link_to 'Create New Article', new_article_path,
            class: 'btn btn-primary' %>

app/views/shared/_author_info.html.erb
<%= link_to gravatar_for(current_author, size: 50), current_author %>
<h1><%= current_author.name %></h1>
<span><%= link_to 'view my profile', current_author %></span>
<span><%= pluralize(current_author.articles.count, 'article') %></span>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, 'error') %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_favorited.html.erb
<% @article %>
<div class="favorites">
    <strong id="favorite" class="favo">
      <%= @article.favoraiters.count %>
    </strong>
    Other Marked This as Favorite
</div>

app/views/shared/_favorites.html.erb
<% @author ||= current_author %>
<div class="favorites">
  <a href="<%= favorites_author_path(@author) %>">
    <strong id="favorite" class="favo">
      <%= @author.favorites.count %>
    </strong>
    Favorite Articles
  </a>
</div>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="articles">
      <% cache @feed_items do %>
        <%= render @feed_items %>
      <% end %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_stats.html.erb
<% @author ||= current_author %>
<div class="stats">
  <a href="<%= following_author_path(@author) %>">
    <strong id="following" class="stat">
      <%= @author.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_author_path(@author) %>">
    <strong id="followers" class="stat">
      <%= @author.followers.count %>
    </strong>
    followers
  </a>
</div>