config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/help', to: 'static_pages#help', as: 'help'

  get '/signup', to: 'authors#new', as: 'signup'
  post '/signup', to: 'authors#create', as: 'register'

  get    '/login',   to: 'sessions#new', as: 'signin'
  post   '/login',   to: 'sessions#create', as: 'login'
  delete '/logout',  to: 'sessions#destroy', as: 'logout'

  get '/feed', to: 'authors#feed', as: 'feed'

  resources :articles

  # resources :authors
  resources :authors do
    member do
      get :following, :followers, :favorites
    end
  end

  resources :follows, only: [:create, :destroy]

  resources :favorites, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/', to: 'static_pages#home', as: 'home'
  root 'static_pages#home'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">SharedBlog</a>
    by <a href="#">Eslam G. Khoga</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Help', help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to 'SharedBlog', root_path, id: 'logo' %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home',   root_path %></li>
        <li><%= link_to 'Authors', authors_path %></li>
        <li><%= link_to 'Articles', articles_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Help',   help_path %></li>
        <% if logged_in? %>
            <li class='dropdown'>
              <a href='#' class='dropdown-toggle' data-toggle='dropdown'>
                Account <b class="caret"></b>
              </a>
              <ul class='dropdown-menu'>
                <li><%= link_to 'Create Article', new_article_path %></li>
                <li><%= link_to 'My Feed', feed_path %></li>
                <li><%= link_to 'Profile', current_author %></li>
                <li><%= link_to 'Settings', edit_author_path(current_author) %><li>
                <li class="divider"></li>
                <li>
                  <%= link_to 'Log out', logout_path, method: :delete %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to 'Log in', login_path %></li>
        <% end %>
      </ul>

    </nav>

  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= render 'layouts/rails_default' %>
  <%= render 'layouts/shim' %>

</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>